//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace ZWave.Configuration {
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Collections.ObjectModel;
    
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NetworkKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte classField;
        
        private byte[] valueField;
        
        private byte[] testValueField;
        
        private bool isEnabledField;
        
        public NetworkKey() {
            this.isEnabledField = true;
        }
        
        [XmlAttributeAttribute()]
        public byte Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] TestValue {
            get {
                return this.testValueField;
            }
            set {
                this.testValueField = value;
                this.RaisePropertyChanged("TestValue");
            }
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(true)]
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
                this.RaisePropertyChanged("IsEnabled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [Serializable]
    public partial class SecurityExtension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keysField;
        
        private byte[] commandClassesField;
        
        [XmlAttributeAttribute()]
        public string Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("Keys");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] CommandClasses {
            get {
                return this.commandClassesField;
            }
            set {
                this.commandClassesField = value;
                this.RaisePropertyChanged("CommandClasses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TestParametersS2Settings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isEnabledField;
        
        private string parameterTypeField;
        
        private byte[] valueField;
        
        public TestParametersS2Settings() {
            this.isEnabledField = true;
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(true)]
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
                this.RaisePropertyChanged("IsEnabled");
            }
        }
        
        [XmlAttributeAttribute()]
        public string ParameterType {
            get {
                return this.parameterTypeField;
            }
            set {
                this.parameterTypeField = value;
                this.RaisePropertyChanged("ParameterType");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TestFrameS2Settings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isEnabledField;
        
        private string frameTypeField;
        
        private int delayField;
        
        private bool delayFieldSpecified;
        
        private bool isEncryptedField;
        
        private bool isEncryptedFieldSpecified;
        
        private bool isMulticastField;
        
        private bool isMulticastFieldSpecified;
        
        private bool isBroadcastField;
        
        private bool isBroadcastFieldSpecified;
        
        private byte[] commandField;
        
        private byte[] networkKeyField;
        
        private bool isTempField;
        
        private bool isTempFieldSpecified;
        
        public TestFrameS2Settings() {
            this.isEnabledField = true;
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(true)]
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
                this.RaisePropertyChanged("IsEnabled");
            }
        }
        
        [XmlAttributeAttribute()]
        public string FrameType {
            get {
                return this.frameTypeField;
            }
            set {
                this.frameTypeField = value;
                this.RaisePropertyChanged("FrameType");
            }
        }
        
        [XmlAttributeAttribute()]
        public int Delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
                this.RaisePropertyChanged("Delay");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelaySpecified {
            get {
                return this.delayFieldSpecified;
            }
            set {
                this.delayFieldSpecified = value;
                this.RaisePropertyChanged("DelaySpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsEncrypted {
            get {
                return this.isEncryptedField;
            }
            set {
                this.isEncryptedField = value;
                this.RaisePropertyChanged("IsEncrypted");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsEncryptedSpecified {
            get {
                return this.isEncryptedFieldSpecified;
            }
            set {
                this.isEncryptedFieldSpecified = value;
                this.RaisePropertyChanged("IsEncryptedSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsMulticast {
            get {
                return this.isMulticastField;
            }
            set {
                this.isMulticastField = value;
                this.RaisePropertyChanged("IsMulticast");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsMulticastSpecified {
            get {
                return this.isMulticastFieldSpecified;
            }
            set {
                this.isMulticastFieldSpecified = value;
                this.RaisePropertyChanged("IsMulticastSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsBroadcast {
            get {
                return this.isBroadcastField;
            }
            set {
                this.isBroadcastField = value;
                this.RaisePropertyChanged("IsBroadcast");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsBroadcastSpecified {
            get {
                return this.isBroadcastFieldSpecified;
            }
            set {
                this.isBroadcastFieldSpecified = value;
                this.RaisePropertyChanged("IsBroadcastSpecified");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
                this.RaisePropertyChanged("Command");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] NetworkKey {
            get {
                return this.networkKeyField;
            }
            set {
                this.networkKeyField = value;
                this.RaisePropertyChanged("NetworkKey");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsTemp {
            get {
                return this.isTempField;
            }
            set {
                this.isTempField = value;
                this.RaisePropertyChanged("IsTemp");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsTempSpecified {
            get {
                return this.isTempFieldSpecified;
            }
            set {
                this.isTempFieldSpecified = value;
                this.RaisePropertyChanged("IsTempSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TestExtensionS2Settings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isEnabledField;
        
        private string actionField;
        
        private string extensionTypeField;
        
        private string messageTypeField;
        
        private bool isEncryptedField;
        
        private bool isEncryptedFieldSpecified;
        
        private byte[] valueField;
        
        private int numOfUsageField;
        
        private bool numOfUsageFieldSpecified;
        
        private bool isMoreToFollowField;
        
        private bool isMoreToFollowFieldSpecified;
        
        private bool isCriticalField;
        
        private bool isCriticalFieldSpecified;
        
        private byte extensionLengthField;
        
        private bool extensionLengthFieldSpecified;
        
        public TestExtensionS2Settings() {
            this.isEnabledField = true;
            this.actionField = "Add";
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(true)]
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
                this.RaisePropertyChanged("IsEnabled");
            }
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute("Add")]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        [XmlAttributeAttribute()]
        public string ExtensionType {
            get {
                return this.extensionTypeField;
            }
            set {
                this.extensionTypeField = value;
                this.RaisePropertyChanged("ExtensionType");
            }
        }
        
        [XmlAttributeAttribute()]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsEncrypted {
            get {
                return this.isEncryptedField;
            }
            set {
                this.isEncryptedField = value;
                this.RaisePropertyChanged("IsEncrypted");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsEncryptedSpecified {
            get {
                return this.isEncryptedFieldSpecified;
            }
            set {
                this.isEncryptedFieldSpecified = value;
                this.RaisePropertyChanged("IsEncryptedSpecified");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        [XmlAttributeAttribute()]
        public int NumOfUsage {
            get {
                return this.numOfUsageField;
            }
            set {
                this.numOfUsageField = value;
                this.RaisePropertyChanged("NumOfUsage");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool NumOfUsageSpecified {
            get {
                return this.numOfUsageFieldSpecified;
            }
            set {
                this.numOfUsageFieldSpecified = value;
                this.RaisePropertyChanged("NumOfUsageSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsMoreToFollow {
            get {
                return this.isMoreToFollowField;
            }
            set {
                this.isMoreToFollowField = value;
                this.RaisePropertyChanged("IsMoreToFollow");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsMoreToFollowSpecified {
            get {
                return this.isMoreToFollowFieldSpecified;
            }
            set {
                this.isMoreToFollowFieldSpecified = value;
                this.RaisePropertyChanged("IsMoreToFollowSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsCritical {
            get {
                return this.isCriticalField;
            }
            set {
                this.isCriticalField = value;
                this.RaisePropertyChanged("IsCritical");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsCriticalSpecified {
            get {
                return this.isCriticalFieldSpecified;
            }
            set {
                this.isCriticalFieldSpecified = value;
                this.RaisePropertyChanged("IsCriticalSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public byte ExtensionLength {
            get {
                return this.extensionLengthField;
            }
            set {
                this.extensionLengthField = value;
                this.RaisePropertyChanged("ExtensionLength");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool ExtensionLengthSpecified {
            get {
                return this.extensionLengthFieldSpecified;
            }
            set {
                this.extensionLengthFieldSpecified = value;
                this.RaisePropertyChanged("ExtensionLengthSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Node : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Collection<SecurityExtension> securityExtensionField;
        
        private byte idField;
        
        private byte endPointIdField;
        
        private bool endPointIdFieldSpecified;
        
        private byte[] nodeInfoField;
        
        private bool isVirtualField;
        
        private bool isVirtualFieldSpecified;
        
        private byte roleTypeField;
        
        private bool roleTypeFieldSpecified;
        
        private byte[] commandClassesField;
        
        private bool isWakeupIntervalSetField;
        
        private bool isWakeupIntervalSetFieldSpecified;
        
        [XmlElementAttribute("SecurityExtension")]
        public Collection<SecurityExtension> SecurityExtension {
            get {
                return this.securityExtensionField;
            }
            set {
                this.securityExtensionField = value;
                this.RaisePropertyChanged("SecurityExtension");
            }
        }
        
        [XmlAttributeAttribute()]
        public byte Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        [XmlAttributeAttribute()]
        public byte EndPointId {
            get {
                return this.endPointIdField;
            }
            set {
                this.endPointIdField = value;
                this.RaisePropertyChanged("EndPointId");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool EndPointIdSpecified {
            get {
                return this.endPointIdFieldSpecified;
            }
            set {
                this.endPointIdFieldSpecified = value;
                this.RaisePropertyChanged("EndPointIdSpecified");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] NodeInfo {
            get {
                return this.nodeInfoField;
            }
            set {
                this.nodeInfoField = value;
                this.RaisePropertyChanged("NodeInfo");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsVirtual {
            get {
                return this.isVirtualField;
            }
            set {
                this.isVirtualField = value;
                this.RaisePropertyChanged("IsVirtual");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsVirtualSpecified {
            get {
                return this.isVirtualFieldSpecified;
            }
            set {
                this.isVirtualFieldSpecified = value;
                this.RaisePropertyChanged("IsVirtualSpecified");
            }
        }
        
        [XmlAttributeAttribute()]
        public byte RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
                this.RaisePropertyChanged("RoleType");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool RoleTypeSpecified {
            get {
                return this.roleTypeFieldSpecified;
            }
            set {
                this.roleTypeFieldSpecified = value;
                this.RaisePropertyChanged("RoleTypeSpecified");
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] CommandClasses {
            get {
                return this.commandClassesField;
            }
            set {
                this.commandClassesField = value;
                this.RaisePropertyChanged("CommandClasses");
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsWakeupIntervalSet {
            get {
                return this.isWakeupIntervalSetField;
            }
            set {
                this.isWakeupIntervalSetField = value;
                this.RaisePropertyChanged("IsWakeupIntervalSet");
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsWakeupIntervalSetSpecified {
            get {
                return this.isWakeupIntervalSetFieldSpecified;
            }
            set {
                this.isWakeupIntervalSetFieldSpecified = value;
                this.RaisePropertyChanged("IsWakeupIntervalSetSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
