//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace ZWave.Xml.FrameHeader {
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class FrameDefinition : object, INotifyPropertyChanged {
        
        private Collection<RadioFrequency> radioFrequencyField;
        
        private Collection<BaseHeader> baseHeaderField;
        
        private Collection<Header> headerField;
        
        private Collection<DefineSet> defineSetField;
        
        private Collection<HeaderFilter> headerFilterField;
        
        /// <remarks/>
        [XmlElement("RadioFrequency")]
        public Collection<RadioFrequency> RadioFrequency {
            get {
                return this.radioFrequencyField;
            }
            set {
                this.radioFrequencyField = value;
                this.RaisePropertyChanged("RadioFrequency");
            }
        }
        
        /// <remarks/>
        [XmlElement("BaseHeader")]
        public Collection<BaseHeader> BaseHeader {
            get {
                return this.baseHeaderField;
            }
            set {
                this.baseHeaderField = value;
                this.RaisePropertyChanged("BaseHeader");
            }
        }
        
        /// <remarks/>
        [XmlElement("Header")]
        public Collection<Header> Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [XmlElement("DefineSet")]
        public Collection<DefineSet> DefineSet {
            get {
                return this.defineSetField;
            }
            set {
                this.defineSetField = value;
                this.RaisePropertyChanged("DefineSet");
            }
        }
        
        /// <remarks/>
        [XmlElement("HeaderFilter")]
        public Collection<HeaderFilter> HeaderFilter {
            get {
                return this.headerFilterField;
            }
            set {
                this.headerFilterField = value;
                this.RaisePropertyChanged("HeaderFilter");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class RadioFrequency : object, INotifyPropertyChanged {
        
        private string nameField;
        
        private byte codeField;
        
        private byte baseHeaderField;
        
        private string textField;
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte BaseHeader {
            get {
                return this.baseHeaderField;
            }
            set {
                this.baseHeaderField = value;
                this.RaisePropertyChanged("BaseHeader");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ListReference : object, INotifyPropertyChanged {
        
        private string refField;
        
        private string sizeRefField;
        
        private bool isBitmaskField;
        
        private sbyte sizeCorrectionField;
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("Ref");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string SizeRef {
            get {
                return this.sizeRefField;
            }
            set {
                this.sizeRefField = value;
                this.RaisePropertyChanged("SizeRef");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool IsBitmask {
            get {
                return this.isBitmaskField;
            }
            set {
                this.isBitmaskField = value;
                this.RaisePropertyChanged("IsBitmask");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public sbyte SizeCorrection {
            get {
                return this.sizeCorrectionField;
            }
            set {
                this.sizeCorrectionField = value;
                this.RaisePropertyChanged("SizeCorrection");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ComplexReference : object, INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [XmlElement("Destination", typeof(ItemReference))]
        [XmlElement("Destinations", typeof(ListReference))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ItemReference : object, INotifyPropertyChanged {
        
        private string refField;
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("Ref");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class BaseHeader : object, INotifyPropertyChanged {
        
        private Collection<Param> paramField;
        
        private ItemReference homeIdField;
        
        private ItemReference sourceField;
        
        private ItemReference sequenceNumberField;
        
        private ItemReference headerTypeField;
        
        private ItemReference isLTXField;
        
        private byte keyField;
        
        private string nameField;
        
        private string textField;
        
        private string commentField;
        
        /// <remarks/>
        [XmlElement("Param")]
        public Collection<Param> Param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
                this.RaisePropertyChanged("Param");
            }
        }
        
        /// <remarks/>
        public ItemReference HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
                this.RaisePropertyChanged("HomeId");
            }
        }
        
        /// <remarks/>
        public ItemReference Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        public ItemReference SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("SequenceNumber");
            }
        }
        
        /// <remarks/>
        public ItemReference HeaderType {
            get {
                return this.headerTypeField;
            }
            set {
                this.headerTypeField = value;
                this.RaisePropertyChanged("HeaderType");
            }
        }
        
        /// <remarks/>
        public ItemReference IsLTX {
            get {
                return this.isLTXField;
            }
            set {
                this.isLTXField = value;
                this.RaisePropertyChanged("IsLTX");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Param : object, INotifyPropertyChanged {
        
        private Collection<Param> param1Field;
        
        private byte orderField;
        
        private string nameField;
        
        private string textField;
        
        private zwParamType typeField;
        
        private string validValueField;
        
        private string optRefField;
        
        private byte sizeField;
        
        private bool sizeFieldSpecified;
        
        private string sizeRefField;
        
        private sbyte sizeCorrectionField;
        
        private bool sizeCorrectionFieldSpecified;
        
        private byte bitsField;
        
        private string commentField;
        
        private string definesField;
        
        /// <remarks/>
        [XmlElement("Param")]
        public Collection<Param> Param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("Param1");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public zwParamType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ValidValue {
            get {
                return this.validValueField;
            }
            set {
                this.validValueField = value;
                this.RaisePropertyChanged("ValidValue");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string OptRef {
            get {
                return this.optRefField;
            }
            set {
                this.optRefField = value;
                this.RaisePropertyChanged("OptRef");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string SizeRef {
            get {
                return this.sizeRefField;
            }
            set {
                this.sizeRefField = value;
                this.RaisePropertyChanged("SizeRef");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public sbyte SizeCorrection {
            get {
                return this.sizeCorrectionField;
            }
            set {
                this.sizeCorrectionField = value;
                this.RaisePropertyChanged("SizeCorrection");
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SizeCorrectionSpecified {
            get {
                return this.sizeCorrectionFieldSpecified;
            }
            set {
                this.sizeCorrectionFieldSpecified = value;
                this.RaisePropertyChanged("SizeCorrectionSpecified");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Bits {
            get {
                return this.bitsField;
            }
            set {
                this.bitsField = value;
                this.RaisePropertyChanged("Bits");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Defines {
            get {
                return this.definesField;
            }
            set {
                this.definesField = value;
                this.RaisePropertyChanged("Defines");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    public enum zwParamType {
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        HEX,
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        NODE_NUMBER,
        
        /// <remarks/>
        BITMASK,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Header : object, INotifyPropertyChanged {
        
        private Collection<Param> paramField;
        
        private Collection<Validation> validationField;
        
        private ComplexReference destinationField;
        
        private ItemReference hopsField;
        
        private ListReference repeatersField;
        
        private byte keyField;
        
        private string nameField;
        
        private string textField;
        
        private bool isAckField;
        
        private bool isRoutedField;
        
        private bool isErrorField;
        
        private bool isMulticastField;
        
        private byte baseHeaderKeyField;
        
        private string commentField;
        
        /// <remarks/>
        [XmlElement("Param")]
        public Collection<Param> Param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
                this.RaisePropertyChanged("Param");
            }
        }
        
        /// <remarks/>
        [XmlElement("Validation")]
        public Collection<Validation> Validation {
            get {
                return this.validationField;
            }
            set {
                this.validationField = value;
                this.RaisePropertyChanged("Validation");
            }
        }
        
        /// <remarks/>
        public ComplexReference Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [XmlElement(IsNullable=true)]
        public ItemReference Hops {
            get {
                return this.hopsField;
            }
            set {
                this.hopsField = value;
                this.RaisePropertyChanged("Hops");
            }
        }
        
        /// <remarks/>
        [XmlElement(IsNullable=true)]
        public ListReference Repeaters {
            get {
                return this.repeatersField;
            }
            set {
                this.repeatersField = value;
                this.RaisePropertyChanged("Repeaters");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool IsAck {
            get {
                return this.isAckField;
            }
            set {
                this.isAckField = value;
                this.RaisePropertyChanged("IsAck");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool IsRouted {
            get {
                return this.isRoutedField;
            }
            set {
                this.isRoutedField = value;
                this.RaisePropertyChanged("IsRouted");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
                this.RaisePropertyChanged("IsError");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool IsMulticast {
            get {
                return this.isMulticastField;
            }
            set {
                this.isMulticastField = value;
                this.RaisePropertyChanged("IsMulticast");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte BaseHeaderKey {
            get {
                return this.baseHeaderKeyField;
            }
            set {
                this.baseHeaderKeyField = value;
                this.RaisePropertyChanged("BaseHeaderKey");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Validation : object, INotifyPropertyChanged {
        
        private string paramNameField;
        
        private string paramHexValueField;
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string ParamName {
            get {
                return this.paramNameField;
            }
            set {
                this.paramNameField = value;
                this.RaisePropertyChanged("ParamName");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ParamHexValue {
            get {
                return this.paramHexValueField;
            }
            set {
                this.paramHexValueField = value;
                this.RaisePropertyChanged("ParamHexValue");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class DefineSet : object, INotifyPropertyChanged {
        
        private Collection<Define> defineField;
        
        private string nameField;
        
        /// <remarks/>
        [XmlElement("Define")]
        public Collection<Define> Define {
            get {
                return this.defineField;
            }
            set {
                this.defineField = value;
                this.RaisePropertyChanged("Define");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Define : object, INotifyPropertyChanged {
        
        private string keyField;
        
        private string nameField;
        
        private string textField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class HeaderFilter : object, INotifyPropertyChanged {
        
        private byte[] headerCodesField;
        
        private byte orderField;
        
        private string textField;
        
        /// <remarks/>
        [XmlArray()]
        [XmlArrayItem("HeaderCode", IsNullable=false)]
        public byte[] HeaderCodes {
            get {
                return this.headerCodesField;
            }
            set {
                this.headerCodesField = value;
                this.RaisePropertyChanged("HeaderCodes");
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public byte Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="NCName")]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
