#! /bin/bash
### BEGIN INIT INFO
# Provides:          inHausUDPzwave
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop inHaus UDP Zwave Sender Thread
# Description:       inHaus UDP Zwave Sender
### END INIT INFO

. /lib/lsb/init-functions

USER=root
GROUP=root
PIDFILE=/var/run/hyper.pid
CWD=/var/inhaus/hyper
CMD="/var/inhaus/hyper/hyper /dev/ttyUSB_ZStickGen5"

case "$1" in
    start)
        log_daemon_msg "Starting hyper..."
		start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --quiet -g $GROUP --chuid $USER --chdir $CWD --exec /usr/bin/screen -- -c /root/dev/screenrc.conf -DmSL 'hyper' $CMD
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping hyper..."
        start-stop-daemon --stop --retry 5 --signal 2 --pidfile $PIDFILE
        log_end_msg $?
        ;;
    restart)
        log_daemon_msg "Restarting hyper..."
		start-stop-daemon --stop --retry 5 --signal 2 --pidfile $PIDFILE
        start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --quiet -g $GROUP --chuid $USER --chdir $CWD --exec /usr/bin/screen -- -c /root/dev/screenrc.conf -DmSL 'inHausZwave' $CMD
        log_end_msg $?
        ;;
    *)
    echo "Usage: {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

