//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ZWave.Xml.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ZWave.Xml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        internal static string ByteBits {
            get {
                return ResourceManager.GetString("ByteBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit {0}: {1}.
        /// </summary>
        internal static string ByteBitsText {
            get {
                return ResourceManager.GetString("ByteBitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit fields.
        /// </summary>
        internal static string ByteSelBits {
            get {
                return ResourceManager.GetString("ByteSelBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        internal static string ByteSelConst {
            get {
                return ResourceManager.GetString("ByteSelConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has flags.
        /// </summary>
        internal static string ByteSelFlags {
            get {
                return ResourceManager.GetString("ByteSelFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ByteSelValue {
            get {
                return ResourceManager.GetString("ByteSelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ByteValue {
            get {
                return ResourceManager.GetString("ByteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Basic Device &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteBasDev {
            get {
                return ResourceManager.GetString("DeleteBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Basic Device.
        /// </summary>
        internal static string DeleteBasDevCap {
            get {
                return ResourceManager.GetString("DeleteBasDevCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command Class &apos;{0}&apos; and all its Command and Parameters?.
        /// </summary>
        internal static string DeleteCC {
            get {
                return ResourceManager.GetString("DeleteCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command Class.
        /// </summary>
        internal static string DeleteCCCap {
            get {
                return ResourceManager.GetString("DeleteCCCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command &apos;{0}&apos; and all its Parameters?.
        /// </summary>
        internal static string DeleteCmd {
            get {
                return ResourceManager.GetString("DeleteCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Command.
        /// </summary>
        internal static string DeleteCmdCap {
            get {
                return ResourceManager.GetString("DeleteCmdCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Generic Device &apos;{0}&apos; and all its Specific Devices?.
        /// </summary>
        internal static string DeleteGenDev {
            get {
                return ResourceManager.GetString("DeleteGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Generic Device.
        /// </summary>
        internal static string DeleteGenDevCap {
            get {
                return ResourceManager.GetString("DeleteGenDevCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Parameter?.
        /// </summary>
        internal static string DeleteParam {
            get {
                return ResourceManager.GetString("DeleteParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete this Parameter! It contains size information..
        /// </summary>
        internal static string DeleteParamCant1 {
            get {
                return ResourceManager.GetString("DeleteParamCant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete this Parameter! It contains multi array first dimension information..
        /// </summary>
        internal static string DeleteParamCant2 {
            get {
                return ResourceManager.GetString("DeleteParamCant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Parameter.
        /// </summary>
        internal static string DeleteParamCap {
            get {
                return ResourceManager.GetString("DeleteParamCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Specific Device &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteSpecDev {
            get {
                return ResourceManager.GetString("DeleteSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Specific Device.
        /// </summary>
        internal static string DeleteSpecDevCap {
            get {
                return ResourceManager.GetString("DeleteSpecDevCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Variant Group &apos;{0}&apos; and all its Parameters?.
        /// </summary>
        internal static string DeleteVariantGroup {
            get {
                return ResourceManager.GetString("DeleteVariantGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Variant Group.
        /// </summary>
        internal static string DeleteVariantGroupCap {
            get {
                return ResourceManager.GetString("DeleteVariantGroupCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basic Device.
        /// </summary>
        internal static string DlgAddBasDev {
            get {
                return ResourceManager.GetString("DlgAddBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        internal static string DlgAddCmd {
            get {
                return ResourceManager.GetString("DlgAddCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Class.
        /// </summary>
        internal static string DlgAddCmdClass {
            get {
                return ResourceManager.GetString("DlgAddCmdClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Data.
        /// </summary>
        internal static string DlgAddCmdData {
            get {
                return ResourceManager.GetString("DlgAddCmdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Generic Device.
        /// </summary>
        internal static string DlgAddGenDev {
            get {
                return ResourceManager.GetString("DlgAddGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        internal static string DlgAddParm {
            get {
                return ResourceManager.GetString("DlgAddParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Specific Device.
        /// </summary>
        internal static string DlgAddSpecDev {
            get {
                return ResourceManager.GetString("DlgAddSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Basic Device.
        /// </summary>
        internal static string DlgEditBasDev {
            get {
                return ResourceManager.GetString("DlgEditBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command.
        /// </summary>
        internal static string DlgEditCmd {
            get {
                return ResourceManager.GetString("DlgEditCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command Class.
        /// </summary>
        internal static string DlgEditCmdClass {
            get {
                return ResourceManager.GetString("DlgEditCmdClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command Data.
        /// </summary>
        internal static string DlgEditCmdData {
            get {
                return ResourceManager.GetString("DlgEditCmdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Generic Device.
        /// </summary>
        internal static string DlgEditGenDev {
            get {
                return ResourceManager.GetString("DlgEditGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameter.
        /// </summary>
        internal static string DlgEditParm {
            get {
                return ResourceManager.GetString("DlgEditParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Specific Device.
        /// </summary>
        internal static string DlgEditSpecDev {
            get {
                return ResourceManager.GetString("DlgEditSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Device:{0}{1} = 0x{2:x2}.
        /// </summary>
        internal static string EditorBasDev {
            get {
                return ResourceManager.GetString("EditorBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit {0}:{1}{2}.
        /// </summary>
        internal static string EditorBit {
            get {
                return ResourceManager.GetString("EditorBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Class:{0}{1} = 0x{2:X2}.
        /// </summary>
        internal static string EditorClass {
            get {
                return ResourceManager.GetString("EditorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command:{0}{1} = 0x{2:X2}.
        /// </summary>
        internal static string EditorCommand {
            get {
                return ResourceManager.GetString("EditorCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        internal static string EditorData {
            get {
                return ResourceManager.GetString("EditorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0:X2} = {1}.
        /// </summary>
        internal static string EditorEnum {
            get {
                return ResourceManager.GetString("EditorEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Device:{0}{1} = 0x{2:X2}.
        /// </summary>
        internal static string EditorGenDev {
            get {
                return ResourceManager.GetString("EditorGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (multi array: first dimension info in BYTE {0}).
        /// </summary>
        internal static string EditorMultiArray {
            get {
                return ResourceManager.GetString("EditorMultiArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (size info in BYTE {0}, bits {1}).
        /// </summary>
        internal static string EditorSizeInfo {
            get {
                return ResourceManager.GetString("EditorSizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (size is determined by message length).
        /// </summary>
        internal static string EditorSizeInfo2 {
            get {
                return ResourceManager.GetString("EditorSizeInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Device:{0}{1} = 0x{2:X2}.
        /// </summary>
        internal static string EditorSpecDev {
            get {
                return ResourceManager.GetString("EditorSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYTE {0}:{1}{2}.
        /// </summary>
        internal static string EditorTreeParam {
            get {
                return ResourceManager.GetString("EditorTreeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARIANT_GROUP.
        /// </summary>
        internal static string EditorTreeVariantGroup {
            get {
                return ResourceManager.GetString("EditorTreeVariantGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:{0}{1}.
        /// </summary>
        internal static string EditorVersion {
            get {
                return ResourceManager.GetString("EditorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding.
        /// </summary>
        internal static string ErrorAdd {
            get {
                return ResourceManager.GetString("ErrorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available space.
        /// </summary>
        internal static string ErrorNoAvailableSpace {
            get {
                return ResourceManager.GetString("ErrorNoAvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has changed. Save changes?.
        /// </summary>
        internal static string FileChanged {
            get {
                return ResourceManager.GetString("FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string FileChangedCap {
            get {
                return ResourceManager.GetString("FileChangedCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string FileOpenFilter {
            get {
                return ResourceManager.GetString("FileOpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Z-Wave XML File.
        /// </summary>
        internal static string FileOpenTitle {
            get {
                return ResourceManager.GetString("FileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Z-Wave XML File.
        /// </summary>
        internal static string FileSaveTitle {
            get {
                return ResourceManager.GetString("FileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string FindDialog_Close {
            get {
                return ResourceManager.GetString("FindDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find Next.
        /// </summary>
        internal static string FindDialog_FindNext {
            get {
                return ResourceManager.GetString("FindDialog_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered name is already in use..
        /// </summary>
        internal static string InvalidNameUsed {
            get {
                return ResourceManager.GetString("InvalidNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value is illegal. Must be between 0x{0:X2} and ox{1:X2}.
        /// </summary>
        internal static string InvalidValueMinMax {
            get {
                return ResourceManager.GetString("InvalidValueMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value is already in use..
        /// </summary>
        internal static string InvalidValueUsed {
            get {
                return ResourceManager.GetString("InvalidValueUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string LenSelFixed {
            get {
                return ResourceManager.GetString("LenSelFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length determined by size parameter.
        /// </summary>
        internal static string LenSelVarKey {
            get {
                return ResourceManager.GetString("LenSelVarKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length determined by message.
        /// </summary>
        internal static string LenSelVarMes {
            get {
                return ResourceManager.GetString("LenSelVarMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Header Generation Error.
        /// </summary>
        internal static string MainForm_CHGenerationError_Title {
            get {
                return ResourceManager.GetString("MainForm_CHGenerationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string MainForm_Created {
            get {
                return ResourceManager.GetString("MainForm_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS Generation Error.
        /// </summary>
        internal static string MainForm_CSGenerationError_Title {
            get {
                return ResourceManager.GetString("MainForm_CSGenerationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been {1} in the C header output folder..
        /// </summary>
        internal static string MainForm_GenerateCHInfo {
            get {
                return ResourceManager.GetString("MainForm_GenerateCHInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been {1} in the C# output folder..
        /// </summary>
        internal static string MainForm_GenerateCSInfo {
            get {
                return ResourceManager.GetString("MainForm_GenerateCSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string MainForm_Line {
            get {
                return ResourceManager.GetString("MainForm_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwritten.
        /// </summary>
        internal static string MainForm_Overwritten {
            get {
                return ResourceManager.GetString("MainForm_Overwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema missing.
        /// </summary>
        internal static string MainForm_XMLSchemaMissing {
            get {
                return ResourceManager.GetString("MainForm_XMLSchemaMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Device is missing key or name in: {0}.
        /// </summary>
        internal static string OpenErrorBasDev {
            get {
                return ResourceManager.GetString("OpenErrorBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate found of Basic Device &apos;{0}&apos;.
        /// </summary>
        internal static string OpenErrorBasDevExists {
            get {
                return ResourceManager.GetString("OpenErrorBasDevExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit error is found in Parameter {0} in &apos;{1} - {2}&apos;.
        /// </summary>
        internal static string OpenErrorBitError {
            get {
                return ResourceManager.GetString("OpenErrorBitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Class is missing key or name in: {0}.
        /// </summary>
        internal static string OpenErrorCC {
            get {
                return ResourceManager.GetString("OpenErrorCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate found of Command Class &apos;{0}&apos;.
        /// </summary>
        internal static string OpenErrorCCExists {
            get {
                return ResourceManager.GetString("OpenErrorCCExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is missing key or name in: {0}.
        /// </summary>
        internal static string OpenErrorCmd {
            get {
                return ResourceManager.GetString("OpenErrorCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate found of Command &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string OpenErrorCmdExists {
            get {
                return ResourceManager.GetString("OpenErrorCmdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong XML tag &apos;{0}&apos; found in Command Class &apos;{1}.
        /// </summary>
        internal static string OpenErrorCmdWrongXML {
            get {
                return ResourceManager.GetString("OpenErrorCmdWrongXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Device is missing key or name in: {0}.
        /// </summary>
        internal static string OpenErrorGenDev {
            get {
                return ResourceManager.GetString("OpenErrorGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate found of Generic Device &apos;{0}&apos;.
        /// </summary>
        internal static string OpenErrorGenDevExists {
            get {
                return ResourceManager.GetString("OpenErrorGenDevExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is missing key or type in: {0}.
        /// </summary>
        internal static string OpenErrorParam {
            get {
                return ResourceManager.GetString("OpenErrorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong XML tag &apos;{0}&apos; found in Command &apos;{1}&apos; in &apos;{2}&apos;.
        /// </summary>
        internal static string OpenErrorParamWrongXML {
            get {
                return ResourceManager.GetString("OpenErrorParamWrongXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Device is missing key or name in: {0}.
        /// </summary>
        internal static string OpenErrorSpecDev {
            get {
                return ResourceManager.GetString("OpenErrorSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate found of Specific Device &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string OpenErrorSpecDevExists {
            get {
                return ResourceManager.GetString("OpenErrorSpecDevExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong XML tag &apos;{0}&apos; found in Generic Device &apos;{1}.
        /// </summary>
        internal static string OpenErrorSpecDevWrongXML {
            get {
                return ResourceManager.GetString("OpenErrorSpecDevWrongXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong or missing field(s) for Parameter {0} in &apos;{1} - {2}&apos;.
        /// </summary>
        internal static string OpenErrorWrongField {
            get {
                return ResourceManager.GetString("OpenErrorWrongField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters of Command &apos;{0}&apos; in &apos;{1}&apos; has been renumbered.
        /// </summary>
        internal static string OpenWarningRenumber {
            get {
                return ResourceManager.GetString("OpenWarningRenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for &apos;{0}&apos; found in &apos;{1}&apos; in &apos;{2}&apos; is not implemented .
        /// </summary>
        internal static string OpenWarningVarGroup {
            get {
                return ResourceManager.GetString("OpenWarningVarGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string OptionsDialog_ErrorBoxCaption {
            get {
                return ResourceManager.GetString("OptionsDialog_ErrorBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Default C Header File Name.
        /// </summary>
        internal static string OptionsDialog_InvalidDefaultCHeaderFile {
            get {
                return ResourceManager.GetString("OptionsDialog_InvalidDefaultCHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Default C# File Name.
        /// </summary>
        internal static string OptionsDialog_InvalidDefaultCSharpFile {
            get {
                return ResourceManager.GetString("OptionsDialog_InvalidDefaultCSharpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C header files (*.h)|*.h.
        /// </summary>
        internal static string OptionsDialog_SelectCHeaderTempalte_Filter {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectCHeaderTempalte_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select C header template file.
        /// </summary>
        internal static string OptionsDialog_SelectCHeaderTemplate_Title {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectCHeaderTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# files (*.cs)|*.cs.
        /// </summary>
        internal static string OptionsDialog_SelectCSharpTemplate_Filter {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectCSharpTemplate_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select C# template file.
        /// </summary>
        internal static string OptionsDialog_SelectCSharpTemplate_Title {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectCSharpTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema (*.xsd)|*.xsd.
        /// </summary>
        internal static string OptionsDialog_SelectXmlSchema_Filter {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectXmlSchema_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML Schema to be used for validation.
        /// </summary>
        internal static string OptionsDialog_SelectXmlSchema_Title {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectXmlSchema_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Byte.
        /// </summary>
        internal static string ParamType1 {
            get {
                return ResourceManager.GetString("ParamType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Bytes.
        /// </summary>
        internal static string ParamType2 {
            get {
                return ResourceManager.GetString("ParamType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Bytes.
        /// </summary>
        internal static string ParamType3 {
            get {
                return ResourceManager.GetString("ParamType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Bytes.
        /// </summary>
        internal static string ParamType4 {
            get {
                return ResourceManager.GetString("ParamType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmask.
        /// </summary>
        internal static string ParamType5 {
            get {
                return ResourceManager.GetString("ParamType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of Bytes.
        /// </summary>
        internal static string ParamType6 {
            get {
                return ResourceManager.GetString("ParamType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ascii.
        /// </summary>
        internal static string ParmIsAscii {
            get {
                return ResourceManager.GetString("ParmIsAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hexadecimal.
        /// </summary>
        internal static string ParmShowHex {
            get {
                return ResourceManager.GetString("ParmShowHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Read Only Attribute?.
        /// </summary>
        internal static string ReadOnlyCap {
            get {
                return ResourceManager.GetString("ReadOnlyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove read only from &apos;{0}&apos;?.
        /// </summary>
        internal static string ReadOnlyOff {
            get {
                return ResourceManager.GetString("ReadOnlyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make &apos;{0}&apos; read only?.
        /// </summary>
        internal static string ReadOnlyOn {
            get {
                return ResourceManager.GetString("ReadOnlyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length bits.
        /// </summary>
        internal static string SizeMaskBits {
            get {
                return ResourceManager.GetString("SizeMaskBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYTE {0}: {1}.
        /// </summary>
        internal static string SizeParm {
            get {
                return ResourceManager.GetString("SizeParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string SizeValue {
            get {
                return ResourceManager.GetString("SizeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC_TYPE_NOT_USED.
        /// </summary>
        internal static string SPECIFIC_TYPE_NOT_USED {
            get {
                return ResourceManager.GetString("SPECIFIC_TYPE_NOT_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Type .
        /// </summary>
        internal static string StdTextBasDev {
            get {
                return ResourceManager.GetString("StdTextBasDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Class .
        /// </summary>
        internal static string StdTextCmdClass {
            get {
                return ResourceManager.GetString("StdTextCmdClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Type .
        /// </summary>
        internal static string StdTextGenDev {
            get {
                return ResourceManager.GetString("StdTextGenDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Type .
        /// </summary>
        internal static string StdTextSpecDev {
            get {
                return ResourceManager.GetString("StdTextSpecDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basic Device.
        /// </summary>
        internal static string SystemLog_Action_AddBas {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Class.
        /// </summary>
        internal static string SystemLog_Action_AddCC {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        internal static string SystemLog_Action_AddCmd {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Generic Device.
        /// </summary>
        internal static string SystemLog_Action_AddGen {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Class Version.
        /// </summary>
        internal static string SystemLog_Action_AddNewVersion {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        internal static string SystemLog_Action_AddParm {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Specific Device.
        /// </summary>
        internal static string SystemLog_Action_AddSpec {
            get {
                return ResourceManager.GetString("SystemLog_Action_AddSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Header Code Generation.
        /// </summary>
        internal static string SystemLog_Action_CHeaderCodeGeneration {
            get {
                return ResourceManager.GetString("SystemLog_Action_CHeaderCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation.
        /// </summary>
        internal static string SystemLog_Action_CodeGeneration {
            get {
                return ResourceManager.GetString("SystemLog_Action_CodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Code Generation.
        /// </summary>
        internal static string SystemLog_Action_CSharpCodeGeneration {
            get {
                return ResourceManager.GetString("SystemLog_Action_CSharpCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit All Command Class Versions for Class.
        /// </summary>
        internal static string SystemLog_Action_EditAllVersionsCC {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditAllVersionsCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit All Command Class Versions for Command.
        /// </summary>
        internal static string SystemLog_Action_EditAllVersionsCmd {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditAllVersionsCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Basic Device.
        /// </summary>
        internal static string SystemLog_Action_EditBas {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command Class.
        /// </summary>
        internal static string SystemLog_Action_EditCC {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Command.
        /// </summary>
        internal static string SystemLog_Action_EditCmd {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Generic Device.
        /// </summary>
        internal static string SystemLog_Action_EditGen {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameter.
        /// </summary>
        internal static string SystemLog_Action_EditParm {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Specific Device.
        /// </summary>
        internal static string SystemLog_Action_EditSpec {
            get {
                return ResourceManager.GetString("SystemLog_Action_EditSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string SystemLog_Action_FileNew {
            get {
                return ResourceManager.GetString("SystemLog_Action_FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Open.
        /// </summary>
        internal static string SystemLog_Action_FileOpen {
            get {
                return ResourceManager.GetString("SystemLog_Action_FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Save.
        /// </summary>
        internal static string SystemLog_Action_FileSave {
            get {
                return ResourceManager.GetString("SystemLog_Action_FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Basic Device.
        /// </summary>
        internal static string SystemLog_Action_RemoveBas {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Command Class.
        /// </summary>
        internal static string SystemLog_Action_RemoveCC {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Command.
        /// </summary>
        internal static string SystemLog_Action_RemoveCmd {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Generic Device.
        /// </summary>
        internal static string SystemLog_Action_RemoveGen {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Parameter.
        /// </summary>
        internal static string SystemLog_Action_RemoveParm {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Specific Device.
        /// </summary>
        internal static string SystemLog_Action_RemoveSpec {
            get {
                return ResourceManager.GetString("SystemLog_Action_RemoveSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Read Only.
        /// </summary>
        internal static string SystemLog_Action_ResetReadOnly {
            get {
                return ResourceManager.GetString("SystemLog_Action_ResetReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Read Only.
        /// </summary>
        internal static string SystemLog_Action_SetReadOnly {
            get {
                return ResourceManager.GetString("SystemLog_Action_SetReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Validation.
        /// </summary>
        internal static string SystemLog_Action_XMLValidation {
            get {
                return ResourceManager.GetString("SystemLog_Action_XMLValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [E].
        /// </summary>
        internal static string SystemLog_Category_Error {
            get {
                return ResourceManager.GetString("SystemLog_Category_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [I].
        /// </summary>
        internal static string SystemLog_Category_Info {
            get {
                return ResourceManager.GetString("SystemLog_Category_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [W].
        /// </summary>
        internal static string SystemLog_Category_Warning {
            get {
                return ResourceManager.GetString("SystemLog_Category_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string SystemLog_Unknown_Action {
            get {
                return ResourceManager.GetString("SystemLog_Unknown_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string SystemLog_Unknown_Category {
            get {
                return ResourceManager.GetString("SystemLog_Unknown_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Device Classes.
        /// </summary>
        internal static string TreeNodeBasicDevice {
            get {
                return ResourceManager.GetString("TreeNodeBasicDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Classes.
        /// </summary>
        internal static string TreeNodeClass {
            get {
                return ResourceManager.GetString("TreeNodeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Classes.
        /// </summary>
        internal static string TreeNodeDevice {
            get {
                return ResourceManager.GetString("TreeNodeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.
        /// </summary>
        internal static string TreeTextClass {
            get {
                return ResourceManager.GetString("TreeTextClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Z-Wave XML Editor.
        /// </summary>
        internal static string WindowCaption {
            get {
                return ResourceManager.GetString("WindowCaption", resourceCulture);
            }
        }
    }
}
